name: build and release

on:
  workflow_dispatch:
  push:
    tags:
     - 'v*'

jobs:
  build-apk:
    runs-on: ubuntu-latest
    outputs:
      signedReleaseFileDir: ${{ steps.split-path.outputs.signedReleaseFileDir }}
      signedReleaseFileName: ${{ steps.split-path.outputs.signedReleaseFileName }}
      signedReleaseFile: ${{ steps.sign-apk.outputs.signedReleaseFile }}
      releaseVersion: ${{ steps.get-version.outputs.version }}

    steps:
    - name: Get the version
      id: get-version
      run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          
    - uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    
    - name: Decode google-services.json
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      run: echo "$FIREBASE_CONFIG" > app/google-services.json
    
    - name: Build with Gradle
      run: ./gradlew assembleAdfreeRelease --stacktrace

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Android Build Tools 29.0.3
      run: |
        yes | sdkmanager "build-tools;29.0.3"

    - name: Sign Adfree APK
      id: sign-apk
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/adfree/release
        signingKeyBase64: ${{ secrets.DEPLOY_SIGN_KEY_JKS_BASE64 }}
        alias: ${{ secrets.DEPLOY_SIGN_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.DEPLOY_SIGN_KEY_JKS_PASSWORD }}
        keyPassword: ${{ secrets.DEPLOY_SIGN_KEY_PASSWORD }}
        
    - name: Split path
      id: split-path
      run: |
        echo "signedReleaseFileDir=$(dirname "${{ steps.sign-apk.outputs.signedReleaseFile }}")" >> $GITHUB_OUTPUT
        echo "signedReleaseFileName=$(basename "${{ steps.sign-apk.outputs.signedReleaseFile }}")" >> $GITHUB_OUTPUT
  
    - name: Save artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.split-path.outputs.signedReleaseFileName }}
        path: ${{ steps.split-path.outputs.signedReleaseFileDir }}
    
  gh-release:
    runs-on: ubuntu-latest
    needs: build-apk
    steps:
    - name: Get artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build-apk.outputs.signedReleaseFileName }}
        path: ${{ needs.build-apk.outputs.signedReleaseFileDir }}

    - name: Upload release to GitHub
      uses: softprops/action-gh-release@v2
      with:
        name: "Adfree APK ${{ needs.build-apk.outputs.releaseVersion }}"
        tag_name: ${{ github.ref_name }}
        body: |
          Autogenerated and signed APK file for the adfree build variant.
        files: ${{ needs.build-apk.outputs.signedReleaseFile }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
